web:
  restart: always
  build: ./
  links:
    - redis:redis
  command: gunicorn --workers 2 --bind 0.0.0.0:5000 -m 007 draft:app
  volumes:
    - .:/usr/src/app

nginx:
  restart: always
  build: ./docker/nginx
  ports:
    - "80:80"
  links:
    - web:web

compass:
  restart: 'no'
  build: ./docker/compass
  command: bash -c 'cd /usr/src/app && compass compile -e production --force'
  volumes:
    - .:/usr/src/app

redis:
  restart: always
  image: redis:3.2-alpine

